### PR TITLE
FOGL-5430: Handle no Description file and multi-line description file case

### PR DESCRIPTION
**Pull request by YashTatkondawar**

### CODE REVIEW

**Comment by YashTatkondawar** [comment]
> Package and Description files are needed for any package. This is the contract we decided and which we need to follow. We should not by pass the description.
> And it does not make any sense to any package without description. (i.e sudo dpkg -I PACKAGE_NAME)

I think you may have misread as we are not bypassing the description.  This PR essentially does - remove a hard rule to have description file, warns if not there and inject based on the type of plugin and name, a generic desc (which we have for most of the plugins). dpkg -l will work as expected.

Additionally, this PR allows description as per standard format instead of rejecting and mark failed because of newline etc. We saw in the recent past where the developer gave the correct desc but packaging failed because of the new line.

**Comment by ashish-jabble** [comment]
>I think you may have misread as we are not bypassing the description

bypassing here I means - exit code 1 is definitely required (As this is package contract and we need it. Even Description file content with plugin name). We need to stick with contract. If contract is missing for package return early! 

> but packaging failed because of the new line

yes multiline support for description is missing since beginning and we have a separate JIRA FOGL-5429 to handle this.

**Comment by praveen-garg** [comment]
> the description is used in various places,

Could we please list, which all/where?

> don't package anything with a description

Description should always be there, Yes. This seems to be fixing the same issue/s: 
    a) if file is there but empty (until now now it was allowed?!)
    b) Allow multiple lines, instead of considering that as a bug in fledge' ecosystem
    c) if user missed to put a file, don't consider a FATAL but choice and use a generic description - * this is subject to controversy/ forced?

I can't make a decision, but it is very hard restriction *in the so called contract*, to force user where s/he can make a choice and we can keep generic.

**Comment by MarkRiddoch** [comment]
The decision is there must be a Description and a Package file if we are to package a repository.  Having a Description that just says this is the xxx plugin is not really helpful. One possibility might be to take the description from the GitHub repository, if it exists and use that if there is no Description file.

At the end of the day the user should be able to give a description of what the package is for, otherwise they soul not be requesting a package.

What we are really saying here is that we have some repositories where the rules have not been followed or the developer was unaware of the requirements. In some ways I would rather have something that checked that everything followed the rules and warned when they didn't.

Every repsository should have certain things if it is to be considered complete

- A licence file
- Correct copyright
- A description of the repository itself in GitHub
- A Package file
- A Description file
- A docs directory with documentation in it

The existence of a Package file and a Description file is mandatory if a package is to be created. Any plugin repository without these should not be packaged.

**Pull request closed without merging**
