### PR TITLE
FOGL-8538 Upgrade of S2OPCUA new toolkit version

### PR DESCRIPTION
**Pull request by ashish-jabble**

### CODE REVIEW

**Review by MarkRiddoch — DISMISSED** [review]

**Review by RVerhoeff — APPROVED** [review]

**Comment by ashish-jabble** [comment]
@RVerhoeff With the given changes it's packaging is failing with below error

```
cp: cannot stat '/usr/local/lib/libs2opc_clientwrapper.so': No such file or directory
```
Verified on both Ub18 and Ub20 having x86_64 architecture.

At packaging side we have added some **preserve links** for the _additional s2opcua package_. Below are the old contents of the package

```
$ sudo dpkg -c fledge-s2opcua_2.5.0_x86_64.deb

-rw-r--r-- ubuntu/ubuntu 3670888 2024-07-01 17:17 ./usr/local/lib/libs2opc_clientserver.so
-rw-r--r-- ubuntu/ubuntu  358176 2024-07-01 17:17 ./usr/local/lib/libs2opc_clientwrapper.so
-rw-r--r-- ubuntu/ubuntu 1624112 2024-07-01 17:17 ./usr/local/lib/libs2opc_common.so
-rw-r--r-- ubuntu/ubuntu  116184 2024-07-01 17:17 ./usr/local/lib/libs2opc_commonwrapper.so
lrwxrwxrwx ubuntu/ubuntu       0 2024-07-01 17:17 ./usr/local/lib/libexpat.so.1 -> libexpat.so.1.9.2
```
Let me know with the new toolkit 1.5.0 version, what are we actually required to make it work.

**Comment by ashish-jabble** [comment]
Fixed above comments.

Seems like we do not need anymore libraries like S2OPC commonwrapper and clientwrapper as per [commit](https://github.com/fledge-iot/fledge-south-s2opcua/pull/63/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a). Therefore removed and now packaging is fine and it passes.
Also enabled shared libraries flag for libexpat as it requires for common additional package.

And new package content be as follows
```
drwxrwxr-x ubuntu/ubuntu     0 2024-07-16 15:58 ./
drwxrwxr-x ubuntu/ubuntu     0 2024-07-16 15:58 ./usr/
drwxrwxr-x ubuntu/ubuntu     0 2024-07-16 15:58 ./usr/local/
drwxrwxr-x ubuntu/ubuntu     0 2024-07-16 15:58 ./usr/local/lib/
-rw-r--r-- ubuntu/ubuntu 5322256 2024-07-16 15:58 ./usr/local/lib/libs2opc_clientserver.so
-rw-r--r-- ubuntu/ubuntu 2591048 2024-07-16 15:58 ./usr/local/lib/libs2opc_common.so
lrwxrwxrwx ubuntu/ubuntu       0 2024-07-16 15:58 ./usr/local/lib/libexpat.so.1 -> libexpat.so.1.9.0
```

**Review by RVerhoeff — APPROVED** [review]
@ashish-jabble ,  you are correct: Systerel refactored their S2OPC Toolkit libraries so the _s2opc_clientwrapper_ and _s2opc_commonwrapper_ libraries no longer exist. I see you changed the _libexpat_ `cmake` command line from _DEXPAT_SHARED_LIBS=OFF_ to _DEXPAT_SHARED_LIBS=ON_. Should I make the same change in _requirements.sh_ in the S2OPC South repository?

**Comment by ashish-jabble** [comment]
> Should I make the same change in requirements.sh in the S2OPC South repository?

@RVerhoeff Not required as such. It is only required at common s2opcua additional package as this package contains an Expat, a C library for parsing XML and OPC UA Toolkit additional libraries.

**Pull request merged**
